export type Localized = { fr: string; en: string };

export type Destination = {
  slug: string;
  name: string;
  region: Localized;
  zone: "coast" | "highlands" | "forest" | "sahel" | "city";
  categories: Array<"nature" | "culture" | "beach" | "adventure" | "city">;
  summary: Localized;
  description: Localized;
  duration: Localized;
  season: Localized;
  image: string;
  imagePage: string;
  credit: string;
  license: string;
  tone: string;
  highlights: Localized[];
};

const commonsImage = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=1280`;

export const destinations: Destination[] = [
  {
    slug: "mont-cameroun",
    name: "Mont Cameroun",
    region: { fr: "Sud-Ouest", en: "South-West" },
    zone: "highlands",
    categories: ["nature", "adventure"],
    summary: { fr: "Une ascension volcanique entre forêt, savane d’altitude et vues sur le golfe de Guinée.", en: "A volcanic ascent through rainforest, high savanna and Gulf of Guinea views." },
    description: { fr: "Le sommet qui domine Buea offre l’une des aventures les plus marquantes du pays. L’ascension se prépare avec un guide reconnu, un équipement adapté et plusieurs jours selon le parcours.", en: "The peak above Buea offers one of the country’s greatest adventures. Plan the climb with a recognised guide, suitable equipment and several days depending on the route." },
    duration: { fr: "3 à 4 jours", en: "3–4 days" },
    season: { fr: "Novembre — février", en: "November — February" },
    image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Landscape_of_Mount_Cameroon.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:Landscape_of_Mount_Cameroon.jpg",
    credit: "Buma Peter", license: "CC BY-SA 4.0", tone: "#17633d",
    highlights: [{ fr: "Départ depuis Buea", en: "Start from Buea" }, { fr: "Paysages volcaniques", en: "Volcanic landscapes" }, { fr: "Guides de montagne locaux", en: "Local mountain guides" }],
  },
  {
    slug: "kribi",
    name: "Kribi & la Lobé",
    region: { fr: "Sud", en: "South" },
    zone: "coast",
    categories: ["beach", "nature", "adventure"],
    summary: { fr: "Plages atlantiques, chutes de la Lobé, villages côtiers et produits de la mer.", en: "Atlantic beaches, Lobé Falls, coastal villages and fresh seafood." },
    description: { fr: "Kribi réunit détente et exploration. Les chutes de la Lobé rejoignent l’océan à proximité de plages, de pirogues et d’adresses conviviales pour prolonger le séjour.", en: "Kribi combines relaxation and discovery. Lobé Falls reach the ocean near beaches, pirogues and welcoming places to extend the stay." },
    duration: { fr: "2 à 4 jours", en: "2–4 days" },
    season: { fr: "Décembre — février", en: "December — February" },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Lob%C3%A9_beach_kribi_Cameroon.jpg/1280px-Lob%C3%A9_beach_kribi_Cameroon.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:Lob%C3%A9_beach_kribi_Cameroon.jpg",
    credit: "Blaizo 237", license: "CC BY-SA 4.0", tone: "#0d6f72",
    highlights: [{ fr: "Chutes de la Lobé", en: "Lobé Falls" }, { fr: "Plages atlantiques", en: "Atlantic beaches" }, { fr: "Cuisine côtière", en: "Coastal cuisine" }],
  },
  {
    slug: "ekom-nkam",
    name: "Ekom-Nkam",
    region: { fr: "Littoral", en: "Littoral" },
    zone: "forest",
    categories: ["nature", "adventure"],
    summary: { fr: "Une cascade spectaculaire dans la forêt du Moungo, près de Melong et Nkongsamba.", en: "A spectacular waterfall in the Moungo forest near Melong and Nkongsamba." },
    description: { fr: "Plusieurs belvédères révèlent la puissance des chutes et la végétation du Moungo. Une excursion guidée permet de mieux comprendre les accès et les conditions du terrain.", en: "Several viewpoints reveal the power of the falls and Moungo vegetation. A guided outing helps visitors understand access and terrain conditions." },
    duration: { fr: "1 journée", en: "1 day" },
    season: { fr: "Juin — novembre", en: "June — November" },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Drone_view_of_the_amazing_Ekom_Nkam_waterfall.jpg/1280px-Drone_view_of_the_amazing_Ekom_Nkam_waterfall.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:Drone_view_of_the_amazing_Ekom_Nkam_waterfall.jpg",
    credit: "Ndijose", license: "CC BY-SA 4.0", tone: "#0b5d45",
    highlights: [{ fr: "Belvédères naturels", en: "Natural viewpoints" }, { fr: "Forêt du Moungo", en: "Moungo rainforest" }, { fr: "Excursion depuis Nkongsamba", en: "Trip from Nkongsamba" }],
  },
  {
    slug: "rhumsiki",
    name: "Rhumsiki",
    region: { fr: "Extrême-Nord", en: "Far North" },
    zone: "sahel",
    categories: ["nature", "culture", "adventure"],
    summary: { fr: "Les pitons des monts Mandara entourent un village kapsiki emblématique.", en: "The Mandara Mountains’ rock spires surround an iconic Kapsiki village." },
    description: { fr: "Les reliefs, maisons de pierre et savoir-faire kapsiki composent une étape unique. Vérifiez les conditions officielles de déplacement avant de planifier le séjour.", en: "Rock formations, stone homes and Kapsiki craft create a singular stop. Check official travel conditions before planning a visit." },
    duration: { fr: "2 à 3 jours", en: "2–3 days" },
    season: { fr: "Novembre — février", en: "November — February" },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Rhumsiki_with_Kapsiki_Peak_%28after_sunrise%29%2C_Far_North_Province_of_Cameroon.jpg/1280px-Rhumsiki_with_Kapsiki_Peak_%28after_sunrise%29%2C_Far_North_Province_of_Cameroon.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:Rhumsiki_with_Kapsiki_Peak_(after_sunrise),_Far_North_Province_of_Cameroon.jpg",
    credit: "Alfred Weidinger", license: "CC BY 2.0", tone: "#a14e2d",
    highlights: [{ fr: "Pics des Mandara", en: "Mandara peaks" }, { fr: "Culture kapsiki", en: "Kapsiki culture" }, { fr: "Lumières du Sahel", en: "Sahel light" }],
  },
  {
    slug: "waza",
    name: "Parc national de Waza",
    region: { fr: "Extrême-Nord", en: "Far North" },
    zone: "sahel",
    categories: ["nature", "adventure"],
    summary: { fr: "Un grand paysage de savane connu pour ses éléphants, girafes, antilopes et oiseaux.", en: "A vast savanna landscape known for elephants, giraffes, antelopes and birds." },
    description: { fr: "Waza est l’un des repères naturels majeurs du Cameroun. L’observation se prépare avec les services autorisés du parc et uniquement lorsque les conditions officielles d’accès le permettent.", en: "Waza is one of Cameroon’s major natural landmarks. Wildlife viewing should be arranged through authorised park services and only when official access conditions allow." },
    duration: { fr: "2 à 3 jours", en: "2–3 days" },
    season: { fr: "Novembre — avril", en: "November — April" },
    image: commonsImage("Elephants around tree in Waza, Cameroon.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Elephants_around_tree_in_Waza,_Cameroon.jpg",
    credit: "Amcaja", license: "CC SA 1.0", tone: "#9b713b",
    highlights: [{ fr: "Savane sahélienne", en: "Sahel savanna" }, { fr: "Observation animalière", en: "Wildlife viewing" }, { fr: "Guide autorisé", en: "Authorised guide" }],
  },
  {
    slug: "benoue",
    name: "Parc national de la Bénoué",
    region: { fr: "Nord", en: "North" },
    zone: "sahel",
    categories: ["nature", "adventure"],
    summary: { fr: "Savanes, cours d’eau et observation de la faune entre Ngaoundéré et Garoua.", en: "Savanna, waterways and wildlife viewing between Ngaoundéré and Garoua." },
    description: { fr: "La Bénoué offre une immersion dans les paysages du Nord autour du fleuve et de ses plaines. L’accès, l’hébergement et les sorties doivent être confirmés auprès des services compétents.", en: "The Bénoué offers an immersion in northern landscapes around the river and plains. Confirm access, lodging and excursions with the relevant services." },
    duration: { fr: "2 à 4 jours", en: "2–4 days" },
    season: { fr: "Novembre — avril", en: "November — April" },
    image: commonsImage("Parc National Benoue.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Parc_National_Benoue.jpg",
    credit: "Ndijose", license: "CC BY-SA 4.0", tone: "#7d7133",
    highlights: [{ fr: "Fleuve Bénoué", en: "Bénoué River" }, { fr: "Safari photo", en: "Photo safari" }, { fr: "Paysages du Nord", en: "Northern landscapes" }],
  },
  {
    slug: "tello",
    name: "Chutes de Tello",
    region: { fr: "Adamaoua", en: "Adamawa" },
    zone: "highlands",
    categories: ["nature", "adventure"],
    summary: { fr: "Une cascade en rideau que l’on découvre depuis les hauteurs de l’Adamaoua.", en: "A curtain waterfall discovered across the Adamawa highlands." },
    description: { fr: "À environ cinquante kilomètres de Ngaoundéré, Tello permet une sortie nature mémorable. La piste et les abords peuvent varier avec la saison : un accompagnement local est recommandé.", en: "About fifty kilometres from Ngaoundéré, Tello makes a memorable nature outing. Track and site conditions vary by season, so local accompaniment is recommended." },
    duration: { fr: "1 journée", en: "1 day" },
    season: { fr: "Octobre — mai", en: "October — May" },
    image: commonsImage("Chutes Tello.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Chutes_Tello.jpg",
    credit: "Marie Barbara", license: "CC BY-SA 4.0", tone: "#1e6a66",
    highlights: [{ fr: "Cascade en rideau", en: "Curtain waterfall" }, { fr: "Plateau de l’Adamaoua", en: "Adamawa plateau" }, { fr: "Excursion guidée", en: "Guided outing" }],
  },
  {
    slug: "lake-awing",
    name: "Lac Awing",
    region: { fr: "Nord-Ouest", en: "North-West" },
    zone: "highlands",
    categories: ["nature", "culture", "adventure"],
    summary: { fr: "Un lac de cratère au cœur des collines verdoyantes des Grassfields.", en: "A crater lake set among the green hills of the Grassfields." },
    description: { fr: "Le lac et son environnement offrent marche, paysages et découverte culturelle près de Bamenda. Avant le départ, vérifiez les conditions régionales et organisez la visite localement.", en: "The lake and its surroundings offer walks, scenery and cultural discovery near Bamenda. Check regional conditions and arrange the visit locally before leaving." },
    duration: { fr: "1 journée", en: "1 day" },
    season: { fr: "Novembre — mars", en: "November — March" },
    image: commonsImage("Lake Awing 2.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Lake_Awing_2.jpg",
    credit: "Achataseh Godwill", license: "CC BY-SA 4.0", tone: "#355d50",
    highlights: [{ fr: "Lac de cratère", en: "Crater lake" }, { fr: "Collines des Grassfields", en: "Grassfields hills" }, { fr: "Balade locale", en: "Local walk" }],
  },
  {
    slug: "foumban",
    name: "Foumban",
    region: { fr: "Ouest", en: "West" },
    zone: "highlands",
    categories: ["culture", "city"],
    summary: { fr: "Palais, musées et ateliers racontent l’histoire et la créativité du royaume bamoun.", en: "Palaces, museums and workshops tell the history and creativity of the Bamoun kingdom." },
    description: { fr: "Le patrimoine royal, les artisans, les marchés et les collections font de Foumban une étape essentielle pour comprendre la profondeur culturelle des Grassfields.", en: "Royal heritage, artisans, markets and collections make Foumban an essential stop for understanding the Grassfields’ cultural depth." },
    duration: { fr: "1 à 2 jours", en: "1–2 days" },
    season: { fr: "Toute l’année", en: "Year-round" },
    image: "https://upload.wikimedia.org/wikipedia/commons/2/23/La_porte_principale_du_sultanat_de_Foumban.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:La_porte_principale_du_sultanat_de_Foumban.jpg",
    credit: "Ruetoyota", license: "CC BY-SA 3.0", tone: "#8d2f26",
    highlights: [{ fr: "Patrimoine bamoun", en: "Bamoun heritage" }, { fr: "Route des artisans", en: "Artisans’ quarter" }, { fr: "Musées et palais", en: "Museums and palace" }],
  },
  {
    slug: "limbe",
    name: "Limbé & jardin botanique",
    region: { fr: "Sud-Ouest", en: "South-West" },
    zone: "coast",
    categories: ["nature", "beach", "city"],
    summary: { fr: "Jardin tropical, plages de sable sombre et vues sur le mont Cameroun.", en: "Tropical gardens, dark-sand beaches and views of Mount Cameroon." },
    description: { fr: "Limbé réunit patrimoine botanique, littoral volcanique, faune protégée et cuisine côtière. C’est une base pratique pour découvrir le Fako sans précipiter le programme.", en: "Limbe combines botanical heritage, volcanic coast, protected wildlife and coastal food. It is a practical base for exploring Fako at a relaxed pace." },
    duration: { fr: "2 à 3 jours", en: "2–3 days" },
    season: { fr: "Novembre — février", en: "November — February" },
    image: commonsImage("Botanic garden limbe54.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Botanic_garden_limbe54.jpg",
    credit: "Sergelowe", license: "CC BY-SA 4.0", tone: "#19584a",
    highlights: [{ fr: "Jardin botanique", en: "Botanic garden" }, { fr: "Plages volcaniques", en: "Volcanic beaches" }, { fr: "Base du Fako", en: "Fako base" }],
  },
  {
    slug: "yaounde",
    name: "Yaoundé",
    region: { fr: "Centre", en: "Centre" },
    zone: "city",
    categories: ["city", "culture"],
    summary: { fr: "La capitale aux collines, entre musées, marchés, jardins et cuisine contemporaine.", en: "The hilltop capital, shaped by museums, markets, gardens and contemporary food." },
    description: { fr: "Yaoundé est un excellent point de départ pour comprendre le Cameroun urbain. Ses quartiers, institutions culturelles et tables permettent une première immersion accessible.", en: "Yaoundé is an excellent gateway to urban Cameroon. Its neighbourhoods, cultural institutions and restaurants offer an approachable first immersion." },
    duration: { fr: "2 à 3 jours", en: "2–3 days" },
    season: { fr: "Toute l’année", en: "Year-round" },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Views_of_Yaounde_Cameroon_05.jpg/1280px-Views_of_Yaounde_Cameroon_05.jpg",
    imagePage: "https://commons.wikimedia.org/wiki/File:Views_of_Yaounde_Cameroon_05.jpg",
    credit: "Kateregga1", license: "CC BY-SA 4.0", tone: "#244d45",
    highlights: [{ fr: "Musées et galeries", en: "Museums and galleries" }, { fr: "Marchés de la capitale", en: "Capital markets" }, { fr: "Cuisine camerounaise", en: "Cameroonian food" }],
  },
  {
    slug: "dja",
    name: "Réserve de faune du Dja",
    region: { fr: "Est", en: "East" },
    zone: "forest",
    categories: ["nature", "adventure"],
    summary: { fr: "Une vaste forêt du bassin du Congo presque encerclée par le fleuve Dja.", en: "A vast Congo Basin rainforest almost encircled by the Dja River." },
    description: { fr: "Classée au patrimoine mondial, la réserve se distingue par une biodiversité exceptionnelle et une forêt largement intacte. Une visite exige une préparation sérieuse avec les services de conservation et des guides locaux.", en: "World Heritage-listed, the reserve stands out for exceptional biodiversity and largely intact forest. A visit requires careful preparation with conservation services and local guides." },
    duration: { fr: "3 à 5 jours", en: "3–5 days" },
    season: { fr: "Décembre — février", en: "December — February" },
    image: commonsImage("Dja River and pirogue.JPG"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Dja_River_and_pirogue.JPG",
    credit: "Amcaja", license: "CC BY-SA 3.0", tone: "#153f2e",
    highlights: [{ fr: "Patrimoine mondial", en: "World Heritage" }, { fr: "Forêt du bassin du Congo", en: "Congo Basin forest" }, { fr: "Expédition encadrée", en: "Guided expedition" }],
  },
  {
    slug: "lobeke",
    name: "Parc national de Lobéké",
    region: { fr: "Est", en: "East" },
    zone: "forest",
    categories: ["nature", "adventure"],
    summary: { fr: "Clairières forestières et faune du bassin du Congo au sein du Trinational de la Sangha.", en: "Forest clearings and Congo Basin wildlife within the Sangha Trinational." },
    description: { fr: "Lobéké protège une mosaïque de forêts et de clairières fréquentées par une faune remarquable. L’accès est une véritable expédition à organiser avec les autorités et opérateurs compétents.", en: "Lobéké protects a mosaic of forests and clearings used by remarkable wildlife. Access is a true expedition to arrange with the relevant authorities and operators." },
    duration: { fr: "4 à 6 jours", en: "4–6 days" },
    season: { fr: "Décembre — février", en: "December — February" },
    image: commonsImage("Lobéké buffalo.jpg"),
    imagePage: "https://commons.wikimedia.org/wiki/File:Lob%C3%A9k%C3%A9_buffalo.jpg",
    credit: "Amcaja", license: "CC BY-SA 2.5", tone: "#173c2d",
    highlights: [{ fr: "Trinational de la Sangha", en: "Sangha Trinational" }, { fr: "Clairières forestières", en: "Forest clearings" }, { fr: "Séjour encadré", en: "Guided stay" }],
  },
];

export const getDestination = (slug: string) => destinations.find((destination) => destination.slug === slug);

export const categoryLabels = {
  all: { fr: "Tout voir", en: "All" },
  nature: { fr: "Nature", en: "Nature" },
  culture: { fr: "Culture", en: "Culture" },
  beach: { fr: "Plages", en: "Beaches" },
  adventure: { fr: "Aventure", en: "Adventure" },
  city: { fr: "Villes", en: "Cities" },
};
