import type { Localized } from "./destinations";

export type TouristPlaceType = "hotel" | "restaurant" | "activity";

export type TouristPlace = {
  id: string;
  name: string;
  type: TouristPlaceType;
  city: string;
  area: Localized;
  coordinates: { lat: number; lng: number };
  summary: Localized;
  details: Localized;
  tags: Localized[];
  destinationSlugs: string[];
  sourceUrl: string;
  image: string;
  imageAlt: Localized;
  imagePage: string;
  imageCredit: string;
  imageLicense: string;
  imageKind: "place" | "context";
};

export const tourismPlaces: TouristPlace[] = [
  {
    id: "hilton-yaounde",
    name: "Hilton Yaoundé",
    type: "hotel",
    city: "Yaoundé",
    area: { fr: "Boulevard du 20 Mai", en: "Boulevard du 20 Mai" },
    coordinates: { lat: 3.86458, lng: 11.51567 },
    summary: {
      fr: "Un point de chute central, proche des musées et du quartier administratif.",
      en: "A central base close to museums and the administrative district.",
    },
    details: {
      fr: "Piscine extérieure · centre de fitness · transfert aéroport sur demande",
      en: "Outdoor pool · fitness centre · airport transfer on request",
    },
    tags: [
      { fr: "Centre-ville", en: "City centre" },
      { fr: "Piscine", en: "Pool" },
      { fr: "Transfert", en: "Transfer" },
    ],
    destinationSlugs: ["yaounde"],
    sourceUrl: "https://www.hilton.com/en/hotels/yaohitw-hilton-yaounde/",
    image: "/places/hilton-yaounde.webp",
    imageAlt: { fr: "Façade du Hilton Yaoundé", en: "Hilton Yaoundé exterior" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Hilton_Hotel_Yaound%C3%A9.JPG",
    imageCredit: "Fawaz.tairou",
    imageLicense: "CC BY-SA 3.0",
    imageKind: "place",
  },
  {
    id: "le-safoutier",
    name: "Le Safoutier",
    type: "restaurant",
    city: "Yaoundé",
    area: { fr: "Hilton Yaoundé", en: "Hilton Yaoundé" },
    coordinates: { lat: 3.86455, lng: 11.51572 },
    summary: {
      fr: "Buffets camerounais et internationaux dans un cadre contemporain.",
      en: "Cameroonian and international buffets in a contemporary setting.",
    },
    details: {
      fr: "Petit-déjeuner · déjeuner · brunch · cuisine locale",
      en: "Breakfast · lunch · brunch · local cuisine",
    },
    tags: [
      { fr: "Cuisine locale", en: "Local cuisine" },
      { fr: "Brunch", en: "Brunch" },
      { fr: "En famille", en: "Family-friendly" },
    ],
    destinationSlugs: ["yaounde"],
    sourceUrl: "https://www.hilton.com/en/hotels/yaohitw-hilton-yaounde/dining/",
    image: "/places/le-safoutier.webp",
    imageAlt: { fr: "Ndolé et banane bouillie, cuisine camerounaise", en: "Ndolé with boiled plantain, Cameroonian cuisine" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Ndol%C3%A8_et_banane_bouillie.jpg",
    imageCredit: "Fawaz.tairou",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "musee-national-yaounde",
    name: "Musée national du Cameroun",
    type: "activity",
    city: "Yaoundé",
    area: { fr: "Quartier du Lac", en: "Lac district" },
    coordinates: { lat: 3.85725, lng: 11.51472 },
    summary: {
      fr: "Une première lecture du pays à travers histoire, arts et patrimoine.",
      en: "An introduction to the country through history, art and heritage.",
    },
    details: {
      fr: "Visite culturelle · centre-ville · horaires à confirmer",
      en: "Cultural visit · city centre · confirm opening hours",
    },
    tags: [
      { fr: "Culture", en: "Culture" },
      { fr: "Histoire", en: "History" },
      { fr: "À l’abri", en: "Indoor" },
    ],
    destinationSlugs: ["yaounde"],
    sourceUrl: "https://www.cameroonembassyusa.org/tourism.php",
    image: "/places/musee-national.webp",
    imageAlt: { fr: "Façade du Musée national du Cameroun à Yaoundé", en: "National Museum of Cameroon exterior in Yaoundé" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_National_du_Cameroun_01.JPG",
    imageCredit: "Z. NGNOGUE",
    imageLicense: "CC BY-SA 3.0",
    imageKind: "place",
  },
  {
    id: "onomo-douala",
    name: "ONOMO Hotel Douala",
    type: "hotel",
    city: "Douala",
    area: { fr: "Bonanjo", en: "Bonanjo" },
    coordinates: { lat: 4.03518, lng: 9.68743 },
    summary: {
      fr: "Un hôtel contemporain qui met en avant design, artisanat et culture du Cameroun.",
      en: "A contemporary hotel celebrating Cameroonian design, craft and culture.",
    },
    details: {
      fr: "Wi-Fi · piscine · navette aéroport · conciergerie",
      en: "Wi-Fi · pool · airport shuttle · concierge",
    },
    tags: [
      { fr: "Aéroport", en: "Airport" },
      { fr: "Piscine", en: "Pool" },
      { fr: "Conciergerie", en: "Concierge" },
    ],
    destinationSlugs: ["mont-cameroun", "ekom-nkam"],
    sourceUrl: "https://www.onomohotels.com/en/hotel/onomo-hotel-douala/",
    image: "/places/onomo-douala.webp",
    imageAlt: { fr: "Façade de l’ONOMO Hotel Douala à Bonanjo", en: "ONOMO Hotel Douala exterior in Bonanjo" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Onomo_Hotel_Douala_Bonanjo.jpg",
    imageCredit: "Serieminou",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "place",
  },
  {
    id: "o-restaurant",
    name: "O’Restaurant",
    type: "restaurant",
    city: "Douala",
    area: { fr: "ONOMO, Bonanjo", en: "ONOMO, Bonanjo" },
    coordinates: { lat: 4.0352, lng: 9.68748 },
    summary: {
      fr: "Un buffet généreux construit autour de produits locaux et de saveurs tropicales.",
      en: "A generous buffet centred on local produce and tropical flavours.",
    },
    details: {
      fr: "Buffet · produits locaux · service continu annoncé",
      en: "Buffet · local produce · continuous service advertised",
    },
    tags: [
      { fr: "Produits locaux", en: "Local produce" },
      { fr: "Buffet", en: "Buffet" },
      { fr: "En famille", en: "Family-friendly" },
    ],
    destinationSlugs: ["mont-cameroun", "ekom-nkam"],
    sourceUrl: "https://www.onomohotels.com/en/hotel/onomo-hotel-douala/",
    image: "/places/o-restaurant.webp",
    imageAlt: { fr: "Sanga, plat camerounais à base de maïs et de feuilles", en: "Sanga, a Cameroonian corn and leafy-green dish" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Le_Sanga..%21%21.jpg",
    imageCredit: "Ishtar19",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "k-hotel-douala",
    name: "K Hotel Douala",
    type: "hotel",
    city: "Douala",
    area: { fr: "729 rue Christian Tobie Kuoh, Bonanjo", en: "729 Christian Tobie Kuoh Street, Bonanjo" },
    coordinates: { lat: 4.0418, lng: 9.6879 },
    summary: {
      fr: "Une adresse urbaine proche du musée maritime et des repères de Bonanjo.",
      en: "An urban stay close to the Maritime Museum and Bonanjo landmarks.",
    },
    details: {
      fr: "Piscine · Wi-Fi · restaurant · terrasse",
      en: "Pool · Wi-Fi · restaurant · terrace",
    },
    tags: [
      { fr: "Bonanjo", en: "Bonanjo" },
      { fr: "Piscine", en: "Pool" },
      { fr: "Musées proches", en: "Near museums" },
    ],
    destinationSlugs: ["mont-cameroun", "ekom-nkam"],
    sourceUrl: "https://www.khoteldouala.com/",
    image: "/places/k-hotel.webp",
    imageAlt: { fr: "Scène urbaine à Bonanjo, quartier du K Hotel", en: "Bonanjo streetscape, the K Hotel district" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Moving_in_bonanjo.jpg",
    imageCredit: "Minette Lontsie",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "kotcha-restaurant",
    name: "Kotcha Restaurant",
    type: "restaurant",
    city: "Douala",
    area: { fr: "K Hotel, Bonanjo", en: "K Hotel, Bonanjo" },
    coordinates: { lat: 4.04182, lng: 9.68793 },
    summary: {
      fr: "Une table contemporaine avec une cuisine de saison servie toute la journée.",
      en: "Contemporary all-day dining shaped by seasonal ingredients.",
    },
    details: {
      fr: "Petit-déjeuner · déjeuner · dîner · cadre contemporain",
      en: "Breakfast · lunch · dinner · contemporary setting",
    },
    tags: [
      { fr: "Toute la journée", en: "All-day dining" },
      { fr: "Produits de saison", en: "Seasonal produce" },
      { fr: "En famille", en: "Family-friendly" },
    ],
    destinationSlugs: ["mont-cameroun", "ekom-nkam"],
    sourceUrl: "https://www.khoteldouala.com/eat-and-drink/kotcha-restaurant/",
    image: "/places/kotcha.webp",
    imageAlt: { fr: "Poulet DG, spécialité camerounaise", en: "Poulet DG, a Cameroonian speciality" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Poulet_D.G_du_Chef_Alex_Bella_Ola.jpeg",
    imageCredit: "MarieroseNN",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "musee-maritime-douala",
    name: "Musée maritime de Douala",
    type: "activity",
    city: "Douala",
    area: { fr: "Bonanjo", en: "Bonanjo" },
    coordinates: { lat: 4.03802, lng: 9.68325 },
    summary: {
      fr: "Le fleuve Wouri, le port et l’histoire maritime racontés dans un musée emblématique.",
      en: "The Wouri River, port and maritime history told through a landmark museum.",
    },
    details: {
      fr: "Mardi à dimanche annoncé · visite individuelle ou en groupe",
      en: "Advertised Tuesday to Sunday · individual or group visits",
    },
    tags: [
      { fr: "Musée", en: "Museum" },
      { fr: "Histoire", en: "History" },
      { fr: "En famille", en: "Family-friendly" },
    ],
    destinationSlugs: ["mont-cameroun", "ekom-nkam"],
    sourceUrl: "https://museemaritime.cm/en/",
    image: "/places/musee-maritime.webp",
    imageAlt: { fr: "Façade du Musée maritime de Douala", en: "Douala Maritime Museum exterior" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_Maritime_de_Douala.jpg",
    imageCredit: "Serieminou",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "place",
  },
  {
    id: "hotel-ilomba",
    name: "Hôtel Ilomba",
    type: "hotel",
    city: "Kribi",
    area: { fr: "Bwambe, près des chutes de la Lobé", en: "Bwambe, near the Lobé Falls" },
    coordinates: { lat: 2.8825, lng: 9.8918 },
    summary: {
      fr: "Un séjour en bord d’océan, entre jardin tropical et excursions dans le Sud.",
      en: "An oceanfront stay between tropical gardens and southern excursions.",
    },
    details: {
      fr: "Plage · restaurant · expériences · bien-être",
      en: "Beach · restaurant · experiences · wellness",
    },
    tags: [
      { fr: "Bord de mer", en: "Seafront" },
      { fr: "Jardin", en: "Garden" },
      { fr: "Excursions", en: "Excursions" },
    ],
    destinationSlugs: ["kribi"],
    sourceUrl: "https://hotelilomba.com/en/",
    image: "/places/hotel-ilomba.webp",
    imageAlt: { fr: "Coucher de soleil sur la plage de Kribi", en: "Sunset over Kribi beach" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Dusk_on_the_beach_of_Kribi-Cameroon_with_the_visible_new_moon_on_a_clear_sky_in_spring.jpg",
    imageCredit: "WaiKum",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "le-baobab-ilomba",
    name: "Le Baobab",
    type: "restaurant",
    city: "Kribi",
    area: { fr: "Hôtel Ilomba, Bwambe", en: "Hotel Ilomba, Bwambe" },
    coordinates: { lat: 2.88252, lng: 9.89184 },
    summary: {
      fr: "Cuisine africaine, inspirations occidentales et produits de saison près de l’océan.",
      en: "African cuisine, Western influences and seasonal produce by the ocean.",
    },
    details: {
      fr: "Petit-déjeuner · déjeuner · dîner · service quotidien annoncé",
      en: "Breakfast · lunch · dinner · advertised daily service",
    },
    tags: [
      { fr: "Cuisine africaine", en: "African cuisine" },
      { fr: "Produits de saison", en: "Seasonal produce" },
      { fr: "Océan", en: "Ocean" },
    ],
    destinationSlugs: ["kribi"],
    sourceUrl: "https://hotelilomba.com/en/restaurant-bar/",
    image: "/places/le-baobab.webp",
    imageAlt: { fr: "Ndolé et plantains mûrs, cuisine camerounaise", en: "Ndolé and ripe plantains, Cameroonian cuisine" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Ndole_and_Ripe_Plantains.jpg",
    imageCredit: "Giftcup",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "chutes-lobe",
    name: "Chutes de la Lobé",
    type: "activity",
    city: "Kribi",
    area: { fr: "Route côtière au sud de Kribi", en: "Coastal road south of Kribi" },
    coordinates: { lat: 2.887, lng: 9.893 },
    summary: {
      fr: "Une rencontre spectaculaire entre cascades, végétation et Atlantique.",
      en: "A spectacular meeting point between waterfalls, vegetation and the Atlantic.",
    },
    details: {
      fr: "Guide local recommandé · accès et météo à vérifier",
      en: "Local guide recommended · check access and weather",
    },
    tags: [
      { fr: "Nature", en: "Nature" },
      { fr: "Photographie", en: "Photography" },
      { fr: "Guide local", en: "Local guide" },
    ],
    destinationSlugs: ["kribi"],
    sourceUrl: "https://whc.unesco.org/en/activities/414/",
    image: "/places/chutes-lobe.webp",
    imageAlt: { fr: "Les chutes de la Lobé rejoignant l’Atlantique à Kribi", en: "Lobé Falls meeting the Atlantic near Kribi" },
    imagePage: "https://commons.wikimedia.org/wiki/File:LOB%C3%89_Falls_Kribi.jpg",
    imageCredit: "Emerymakini",
    imageLicense: "CC BY 4.0",
    imageKind: "place",
  },
  {
    id: "mountain-hotel-buea",
    name: "Mountain Hotel Buea",
    type: "hotel",
    city: "Buea",
    area: { fr: "Au pied du Mont Cameroun", en: "At the foot of Mount Cameroon" },
    coordinates: { lat: 4.1593, lng: 9.24354 },
    summary: {
      fr: "Une base historique à Buea pour découvrir la ville et préparer la montagne.",
      en: "A long-standing Buea base for exploring town and preparing for the mountain.",
    },
    details: {
      fr: "Parking · Wi-Fi · restauration · vue montagne",
      en: "Parking · Wi-Fi · dining · mountain views",
    },
    tags: [
      { fr: "Montagne", en: "Mountain" },
      { fr: "Parking", en: "Parking" },
      { fr: "Buea", en: "Buea" },
    ],
    destinationSlugs: ["mont-cameroun"],
    sourceUrl: "https://mountainhotelcameroon.com/",
    image: "/places/mountain-hotel.webp",
    imageAlt: { fr: "Palais du gouverneur à Buea, repère historique de la ville", en: "Governor’s Palace in Buea, a historic city landmark" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Governor%27s_Palace_Buea_2014.jpg",
    imageCredit: "Bdx",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "context",
  },
  {
    id: "mont-cameroun-ascension",
    name: "Mont Cameroun",
    type: "activity",
    city: "Buea",
    area: { fr: "Départ depuis Buea", en: "Start from Buea" },
    coordinates: { lat: 4.203, lng: 9.1705 },
    summary: {
      fr: "Une expérience volcanique majeure à organiser avec un guide de montagne reconnu.",
      en: "A major volcanic experience to organise with a recognised mountain guide.",
    },
    details: {
      fr: "Guide indispensable · préparation physique · météo à vérifier",
      en: "Guide essential · physical preparation · check weather",
    },
    tags: [
      { fr: "Randonnée", en: "Hiking" },
      { fr: "Volcan", en: "Volcano" },
      { fr: "Guide", en: "Guide" },
    ],
    destinationSlugs: ["mont-cameroun"],
    sourceUrl: "https://discover-cameroon.com/en/tours/",
    image: "/places/mont-cameroun.webp",
    imageAlt: { fr: "Randonneurs sur les pentes du Mont Cameroun", en: "Hikers on the slopes of Mount Cameroon" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Athele_au_Mont_Cameroun.jpg",
    imageCredit: "Edtamba",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "place",
  },
  {
    id: "ekom-nkam-waterfalls",
    name: "Chutes d’Ekom-Nkam",
    type: "activity",
    city: "Melong",
    area: { fr: "Moungo, près de Nkongsamba", en: "Moungo, near Nkongsamba" },
    coordinates: { lat: 5.0697, lng: 9.9488 },
    summary: {
      fr: "Une grande cascade au cœur d’un paysage tropical spectaculaire.",
      en: "A major waterfall set in a spectacular tropical landscape.",
    },
    details: {
      fr: "Excursion à la journée · chaussures adaptées · guide recommandé",
      en: "Day trip · suitable footwear · guide recommended",
    },
    tags: [
      { fr: "Cascade", en: "Waterfall" },
      { fr: "Forêt", en: "Forest" },
      { fr: "Excursion", en: "Day trip" },
    ],
    destinationSlugs: ["ekom-nkam"],
    sourceUrl: "https://discover-cameroon.com/en/tours/",
    image: "/places/ekom-nkam.webp",
    imageAlt: { fr: "Les chutes d’Ekom-Nkam dans la forêt du Moungo", en: "Ekom-Nkam Falls in the Moungo forest" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Chutes_d%27Ekom_Nkam.jpg",
    imageCredit: "Razdagger",
    imageLicense: "CC BY-SA 3.0",
    imageKind: "place",
  },
  {
    id: "palais-royal-foumban",
    name: "Palais royal de Foumban",
    type: "activity",
    city: "Foumban",
    area: { fr: "Centre historique", en: "Historic centre" },
    coordinates: { lat: 5.7292, lng: 10.9008 },
    summary: {
      fr: "Le grand repère du patrimoine bamoun, entouré de musées et d’ateliers d’artisans.",
      en: "A landmark of Bamoun heritage surrounded by museums and artisan workshops.",
    },
    details: {
      fr: "Patrimoine · artisanat · visite culturelle",
      en: "Heritage · craft · cultural visit",
    },
    tags: [
      { fr: "Patrimoine", en: "Heritage" },
      { fr: "Artisanat", en: "Craft" },
      { fr: "Musées", en: "Museums" },
    ],
    destinationSlugs: ["foumban"],
    sourceUrl: "https://www.cameroonembassyusa.org/tourism.php",
    image: "/places/palais-foumban.webp",
    imageAlt: { fr: "Entrée du musée du Palais royal de Foumban", en: "Museum entrance at Foumban Royal Palace" },
    imagePage: "https://commons.wikimedia.org/wiki/File:CAM-Foumban-Palais_royal-Entr%C3%A9e_du_mus%C3%A9e.jpg",
    imageCredit: "WILLAV-FR",
    imageLicense: "CC BY-SA 4.0",
    imageKind: "place",
  },
  {
    id: "rhumsiki-paysage",
    name: "Circuit culturel de Rhumsiki",
    type: "activity",
    city: "Rhumsiki",
    area: { fr: "Monts Mandara", en: "Mandara Mountains" },
    coordinates: { lat: 10.488, lng: 13.589 },
    summary: {
      fr: "Paysages rocheux, savoir-faire kapsiki et lumière du Sahel avec accompagnement local.",
      en: "Rock landscapes, Kapsiki craft and Sahel light with local accompaniment.",
    },
    details: {
      fr: "Guide local · conditions régionales et accès à confirmer",
      en: "Local guide · confirm regional conditions and access",
    },
    tags: [
      { fr: "Paysage", en: "Landscape" },
      { fr: "Culture", en: "Culture" },
      { fr: "Guide local", en: "Local guide" },
    ],
    destinationSlugs: ["rhumsiki"],
    sourceUrl: "https://www.cameroonembassyusa.org/tourism.php",
    image: "/places/rhumsiki.webp",
    imageAlt: { fr: "Habitat kapsiki dans le paysage rocheux de Rhumsiki", en: "Kapsiki home in Rhumsiki’s rocky landscape" },
    imagePage: "https://commons.wikimedia.org/wiki/File:Kapsiki_home_in_Rhumsiki.jpg",
    imageCredit: "Amcaja",
    imageLicense: "CC BY-SA 3.0",
    imageKind: "place",
  },
];

export const tourismCities = [...new Set(tourismPlaces.map((place) => place.city))].sort();

export const tourismTypeLabels: Record<TouristPlaceType | "all", Localized> = {
  all: { fr: "Tout voir", en: "All places" },
  hotel: { fr: "Hôtels", en: "Hotels" },
  restaurant: { fr: "Restaurants", en: "Restaurants" },
  activity: { fr: "À faire", en: "Things to do" },
};

export const tourismTypeIcons: Record<TouristPlaceType, string> = {
  hotel: "⌂",
  restaurant: "◒",
  activity: "✦",
};
